# .github/workflows/deploy.yml
name: 🚀 Auto-Deploy Bot & Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            set -e

            echo "=== BOT: Pull code & restart container ==="
            cd ~/site-for-mpu/telegram-wordly-bot
            git fetch origin main
            git reset --hard origin/main

            if docker ps -q --filter name=wordly-bot; then
              docker rm -f wordly-bot
            fi

            docker build -t wordly-bot .
            docker run -d \
              --name wordly-bot \
              --restart unless-stopped \
              --env-file .env \
              -v "$(pwd)/user_activity.json":/app/user_activity.json \
              wordly-bot

            echo "=== SITE: Reset & pull code & reload nginx ==="
            cd ~/site-for-mpu/site
            git fetch origin main
            git reset --hard origin/main

            sudo nginx -s reload

            echo "✅ Deployment complete"

            docker logs --tail 20 wordly-bot
            echo "=== Prune dangling images ==="
            docker image prune --force

            docker logs --tail 20 wordly-bot

            echo "=== Prune dangling images ==="
            docker image prune --force
