name: 🚀 Deploy Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}          # e.g. 158.160.117.222
        username: ${{ secrets.VPS_USER }}      # ваш логин на VPS
        key: ${{ secrets.VPS_SSH_KEY }}        # приватный SSH-ключ
        port: 22                               # обычно 22
        script: |
          set -e
          cd ~/site-for-mpu

          # Сбрасываемся к последнему коммиту main
          git fetch origin main
          git reset --hard origin/main

          # Остановить старый контейнер
          if docker ps -q --filter name=wordly-bot >/dev/null; then
            docker rm -f wordly-bot
          fi

          # Собираем новый образ
          docker build -t wordly-bot .

          # Запускаем контейнер, монтируя весь проект в /app
          docker run -d \
            --name wordly-bot \
            --restart unless-stopped \
            --env-file /app/telegram-wordly-bot/.env \
            -v ~/site-for-mpu:/app \
            wordly-bot

          echo "✅ Bot deployed successfully"

