name: Auto-Deploy Wordly Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT || '22' }}
        script: |
          set -e
          cd ~/site-for-mpu

          echo "=== Sync code ==="
          git fetch origin main
          git reset --hard origin/main

          echo "=== Remove old container ==="
          docker rm -f wordly-bot || true

          echo "=== Build new image ==="
          docker build -t wordly-bot .

          echo "=== Run container ==="
          docker run -d \
            --name wordly-bot \
            --restart unless-stopped \
            --env-file .env \
            -v ~/site-for-mpu:/app \
            wordly-bot

          echo "✅ Bot deployed successfully"