name: 🚀 Deploy Site

on:
  push:
    branches:
      - main
    paths:
      - 'site/**'

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Site via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          port:     ${{ secrets.VPS_PORT || 22 }}
          script: |
            set -e
            cd ~/site-for-mpu/site
            git fetch origin main
            git reset --hard origin/main
            sudo nginx -s reload
            echo "✅ Site deployed"
