# .github/workflows/deploy-site.yml
name: 🚀 Deploy Site & Sync Wordlist

on:
  push:
    branches:
      - main
    paths:
      - 'site/**'
      - '.github/workflows/deploy-site.yml'
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Site & Sync Wordlist via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          port:     ${{ secrets.VPS_PORT || 22 }}
          script: |
            set -xe

            BASE_DIR=/home/${{ secrets.VPS_USER }}/site-for-mpu
            cd $BASE_DIR

            echo "=== Git: fetch & checkout main ==="
            git fetch origin main
            git checkout main

            echo "=== Git: commit VM-side wordlist changes ==="
            if [ -n "$(git status --porcelain telegram-wordly-bot/base_words.json)" ]; then
              git add telegram-wordly-bot/base_words.json
              git commit -m "ci: sync wordlist from VM @ $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
              git push --force origin main
            else
              echo "No VM-side wordlist changes."
            fi

            echo "=== Git: hard-reset to origin/main ==="
            git fetch origin main
            git reset --hard origin/main

            echo "=== Deploy Site ==="
            cd site
            sudo nginx -s reload

            echo "✅ Site deployed and wordlist synced"
