name: Auto-Deploy Wordly Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # чтобы были все коммиты для возможного пуша

    - name: SSH deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}       # e.g. "158.160.117.222"
        username: ${{ secrets.VPS_USER }}   # ваш логин на VPS
        key: ${{ secrets.SHH_PRIVATE_KEY }}     # приватный SSH-ключ
        port: ${{ secrets.VPS_POST }}
        script: |
          set -e

          cd ~/site-for-mpu

          # Убедимся, что рабочая копия синхронизирована
          git fetch origin main
          git reset --hard origin/main

          # Соберём и запустим контейнер
          if docker ps -q --filter name=wordly-bot >/dev/null; then
            docker rm -f wordly-bot
          fi

          docker build -t wordly-bot .
          docker run -d \
            --name wordly-bot \
            --restart unless-stopped \
            --env-file /app/.env \
            -v ~/site-for-mpu:/app \
            wordly-bot

          echo "✅ Bot deployed"

    - name: Push vocabulary changes back to GitHub
      if: ${{ steps.deploy.outcome == 'success' }}
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: '.'              # корень клонированного репо
        commit_message: 'Update vocabulary.json via bot'
        branch: main
        force: true
