# .github/workflows/deploy.yml
name: 🚀 Auto-Deploy Bot & Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Bot and Static Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            set -e

            echo "=== BOT: Pull code & restart container ==="
            cd ~/site-for-mpu/telegram-wordly-bot
            git pull origin main

            # Stop and remove old container if exists
            if docker ps -q --filter name=wordly-bot; then
              docker rm -f wordly-bot
            fi

            # Build and run new bot image
            docker build -t wordly-bot .
            docker run -d \
              --name wordly-bot \
              --restart unless-stopped \
              --env-file .env \
              -v "$(pwd)/user_activity.json":/app/user_activity.json \
              wordly-bot

            echo "=== SITE: Pull code & reload nginx ==="
            cd ~/site-for-mpu/site
            sudo -u sqwirex git pull origin main

            # Reload nginx to pick up new static files
            sudo nginx -s reload

            echo "✅ Deployment complete"

            docker logs --tail 20 wordly-bot

            echo "=== Prune dangling images ==="
            docker image prune --force
