name: 🤖 Deploy Wordly Bot

on:
  push:
    branches:
      - main
    paths:
      - 'telegram-wordly-bot/**'
      - 'Dockerfile'
      - '.github/workflows/deploy-bot.yml'
  workflow_dispatch:

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Bot via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          port:     ${{ secrets.VPS_PORT || 22 }}
          script: |
            set -xe

            BASE_DIR=/home/${{ secrets.VPS_USER }}/site-for-mpu
            cd $BASE_DIR

            echo "=== Git: fetch & checkout main ==="
            git fetch origin main
            git checkout main

            echo "=== Git: commit & push VM-side wordlist changes ==="
            if [ -n "$(git status --porcelain telegram-wordly-bot/base_words.json)" ]; then
              git add telegram-wordly-bot/base_words.json
              git commit -m "ci: sync wordlist from VM @ $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
              git pull --ff-only origin main
              git push origin main
            else
              echo "No VM-side wordlist changes."
            fi

            echo "=== Git: align local to origin/main ==="
            git fetch origin main
            git reset --hard origin/main

            echo "=== Docker: build image ==="
            docker build -t wordly-bot .

            echo "=== Docker: stop & remove old container ==="
            docker rm -f wordly-bot || true

            echo "=== Docker: start new container ==="
            docker run -d \
              --name wordly-bot \
              --restart unless-stopped \
              -v $BASE_DIR/telegram-wordly-bot:/app/telegram-wordly-bot \
              --env-file $BASE_DIR/telegram-wordly-bot/.env \
              wordly-bot

            echo "=== Docker: prune dangling images ==="
            docker image prune -f

            echo "✅ Bot deployed and wordlist synced"